### ISSUE TITLE
Total deaths incorrectly drops to zero

### ISSUE THREAD

**Issue by pearcircuitmike** [owid/monkeypox#2]
For example, the "world" metric shows total deaths drop to zero. This is impacting other countries, like Brazil. A possible solution would be to update the code so the generated file shows "total deaths" as a running total of "new deaths." Looks like that was what was happening until a few days ago - now there's lots of empty/zero values for total deaths.

**Comment by edomt** [comment]
Hi @pearcircuitmike 

I believe this is most likely due to the software or script you're using to import the data, which must be replacing `NA` values with `0` automatically.

In our CSV file, these values are set to `NA` after the last known death:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/7103774/189637568-232edcbc-9123-4757-a6aa-6692891913a6.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/7103774/189637593-d7632053-9e58-457a-b168-b328224682c9.png">

The reason why we don't fill `total_deaths` forward is that some countries report monkeypox data very irregularly, which means we don't always know whether new deaths have occurred since then.
